# Generated by Django 5.1.7 on 2025-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Boys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20),
        ),
    ]
