# Generated by Django 5.1.7 on 2025-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Boys', '0002_alter_deliveryboy_id_alter_deliveryboy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='status',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
