# Generated by Django 5.1.7 on 2025-03-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Boys', '0003_remove_deliveryboy_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='approval_status',
            new_name='status',
        ),
    ]
