# Generated by Django 5.1.7 on 2025-03-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_checkout_status'),
        ('Delivery_Boys', '0004_rename_approval_status_deliveryboy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='assigned', max_length=20)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery_Boys.deliveryboy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.checkout')),
            ],
        ),
    ]
