# Generated by Django 5.1.7 on 2025-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_checkout_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
