# Generated by Django 5.1.7 on 2025-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('homechef', 'Home Chef'), ('delivery boy', 'Delivery Boy')], max_length=20),
        ),
    ]
