# Generated by Django 5.1.7 on 2025-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_chatmessage_checkout_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(max_length=10),
        ),
    ]
