# Generated by Django 5.1.7 on 2025-04-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_chatmessage_checkout_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.orderitem'),
        ),
    ]
