# Generated by Django 5.1.7 on 2025-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_chatmessage_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('customer', 'Customer'), ('chef', 'Chef')], max_length=10),
        ),
    ]
