# Generated by Django 5.1.7 on 2025-04-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_chatmessage_sender'),
        ('Homechef', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homechef.homechef_registration'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
