# Generated by Django 5.1.7 on 2025-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeChef_registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='homechef_photos/')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('dish', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
