# Generated by Django 5.1.7 on 2025-03-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homechef', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Evening Snack', 'Evening Snack'), ('Dinner', 'Dinner')], default='Breakfast', max_length=20),
        ),
    ]
